title: AI Travel Assistant
description: "Voice & Chat Flight Search Engine built with Flutter Clean Architecture, Hybrid Gemini 1.5 Flash LLM & Stygian Dark Documentation Theme."
url: "https://aavvvacado.github.io"
baseurl: "/Ai-travel-booking-assistance"
repository: "aavvvacado/Ai-travel-booking-assistance"
remote_theme: ksauraj/stygian

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

aux_links:
  "GitHub Repository": "https://github.com/aavvvacado/Ai-travel-booking-assistance"

theme_color: "#000000"
